// implemented interface(s)
// ...

// used interfaces
#if defined(TESTHARNESS)
// ...bind to stubs...

// N_Connection
#define N_Connection_ReconnectHandler_Subscribe N_Connection_Stub_ReconnectHandler_Subscribe
#define N_Connection_ReconnectHandler_NetworkDiscovery N_Connection_Stub_ReconnectHandler_NetworkDiscovery
#define N_Connection_ReconnectHandler_Rejoin N_Connection_Stub_ReconnectHandler_Rejoin
#define N_Connection_ReconnectHandler_ReconnectDone N_Connection_Stub_ReconnectHandler_ReconnectDone
#define N_Connection_ReconnectHandler_UnsecureRejoin N_Connection_Stub_ReconnectHandler_UnsecureRejoin

// N_DeviceInfo
#define N_DeviceInfo_GetPrimaryChannelMask N_DeviceInfo_Stub_GetPrimaryChannelMask
#define N_DeviceInfo_GetSecondaryChannelMask N_DeviceInfo_Stub_GetSecondaryChannelMask
#define N_DeviceInfo_GetNetworkChannel N_DeviceInfo_Stub_GetNetworkChannel
#define N_DeviceInfo_GetNetworkExtendedPanId N_DeviceInfo_Stub_GetNetworkExtendedPanId
#define N_DeviceInfo_GetNetworkUpdateId N_DeviceInfo_Stub_GetNetworkUpdateId
#define N_DeviceInfo_GetTrustCenterMode N_DeviceInfo_Stub_GetTrustCenterMode

#else
// ...bind to implementation...

// N_Connection
#define N_Connection_ReconnectHandler_Subscribe N_Connection_ReconnectHandler_Subscribe_Impl
#define N_Connection_ReconnectHandler_NetworkDiscovery N_Connection_ReconnectHandler_NetworkDiscovery_Impl
#define N_Connection_ReconnectHandler_Rejoin N_Connection_ReconnectHandler_Rejoin_Impl
#define N_Connection_ReconnectHandler_ReconnectDone N_Connection_ReconnectHandler_ReconnectDone_Impl
#define N_Connection_ReconnectHandler_UnsecureRejoin N_Connection_ReconnectHandler_UnsecureRejoin_Impl

// N_DeviceInfo
#define N_DeviceInfo_GetPrimaryChannelMask N_DeviceInfo_GetPrimaryChannelMask_Impl
#define N_DeviceInfo_GetSecondaryChannelMask N_DeviceInfo_GetSecondaryChannelMask_Impl
#define N_DeviceInfo_GetNetworkChannel N_DeviceInfo_GetNetworkChannel_Impl
#define N_DeviceInfo_GetNetworkExtendedPanId N_DeviceInfo_GetNetworkExtendedPanId_Impl
#define N_DeviceInfo_GetNetworkUpdateId N_DeviceInfo_GetNetworkUpdateId_Impl
#define N_DeviceInfo_GetTrustCenterMode N_DeviceInfo_GetTrustCenterMode_Impl

#endif
