/************************************************************************//**
  \file zclSimpleMeteringClusterMacroSet.h

  \brief
    The header file describes macros for defining servers block information attribute set of Simple Metering Cluster


  \author
    Atmel Corporation: http://www.atmel.com \n
    Support email: avr@atmel.com

  Copyright (c) 2008-2015, Atmel Corporation. All rights reserved.
  Licensed under Atmel's Limited License Agreement (BitCloudTM).

  \internal
    History:

******************************************************************************/
#ifndef _SIMPLEMETERINGCLUSTERMACROSET_H
#define _SIMPLEMETERINGCLUSTERMACROSET_H

#include <sysRepeatMacro.h>

#define CURRENT_NO_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0900)
#define CURRENT_NO_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0901)
#define CURRENT_NO_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0902)
#define CURRENT_NO_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0903)
#define CURRENT_NO_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0904)
#define CURRENT_NO_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0905)
#define CURRENT_NO_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0906)
#define CURRENT_NO_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0907)
#define CURRENT_NO_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0908)
#define CURRENT_NO_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x0909)
#define CURRENT_NO_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090A)
#define CURRENT_NO_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090B)
#define CURRENT_NO_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090C)
#define CURRENT_NO_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090D)
#define CURRENT_NO_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090E)
#define CURRENT_NO_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x090F)
#define CURRENT_1_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0910)
#define CURRENT_1_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0911)
#define CURRENT_1_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0912)
#define CURRENT_1_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0913)
#define CURRENT_1_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0914)
#define CURRENT_1_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0915)
#define CURRENT_1_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0916)
#define CURRENT_1_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0917)
#define CURRENT_1_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0918)
#define CURRENT_1_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0919)
#define CURRENT_1_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091A)
#define CURRENT_1_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091B)
#define CURRENT_1_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091C)
#define CURRENT_1_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091D)
#define CURRENT_1_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091E)
#define CURRENT_1_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x091F)
#define CURRENT_2_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0920)
#define CURRENT_2_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0921)
#define CURRENT_2_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0922)
#define CURRENT_2_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0923)
#define CURRENT_2_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0924)
#define CURRENT_2_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0925)
#define CURRENT_2_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0926)
#define CURRENT_2_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0927)
#define CURRENT_2_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0928)
#define CURRENT_2_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0929)
#define CURRENT_2_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092A)
#define CURRENT_2_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092B)
#define CURRENT_2_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092C)
#define CURRENT_2_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092D)
#define CURRENT_2_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092E)
#define CURRENT_2_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x092F)
#define CURRENT_3_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0930)
#define CURRENT_3_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0931)
#define CURRENT_3_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0932)
#define CURRENT_3_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0933)
#define CURRENT_3_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0934)
#define CURRENT_3_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0935)
#define CURRENT_3_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0936)
#define CURRENT_3_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0937)
#define CURRENT_3_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0938)
#define CURRENT_3_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0939)
#define CURRENT_3_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093A)
#define CURRENT_3_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093B)
#define CURRENT_3_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093C)
#define CURRENT_3_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093D)
#define CURRENT_3_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093E)
#define CURRENT_3_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x093F)
#define CURRENT_4_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0940)
#define CURRENT_4_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0941)
#define CURRENT_4_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0942)
#define CURRENT_4_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0943)
#define CURRENT_4_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0944)
#define CURRENT_4_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0945)
#define CURRENT_4_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0946)
#define CURRENT_4_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0947)
#define CURRENT_4_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0948)
#define CURRENT_4_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0949)
#define CURRENT_4_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094A)
#define CURRENT_4_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094B)
#define CURRENT_4_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094C)
#define CURRENT_4_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094D)
#define CURRENT_4_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094E)
#define CURRENT_4_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x094F)
#define CURRENT_5_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0950)
#define CURRENT_5_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0951)
#define CURRENT_5_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0952)
#define CURRENT_5_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0953)
#define CURRENT_5_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0954)
#define CURRENT_5_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0955)
#define CURRENT_5_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0956)
#define CURRENT_5_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0957)
#define CURRENT_5_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0958)
#define CURRENT_5_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0959)
#define CURRENT_5_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095A)
#define CURRENT_5_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095B)
#define CURRENT_5_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095C)
#define CURRENT_5_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095D)
#define CURRENT_5_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095E)
#define CURRENT_5_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x095F)
#define CURRENT_6_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0960)
#define CURRENT_6_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0961)
#define CURRENT_6_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0962)
#define CURRENT_6_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0963)
#define CURRENT_6_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0964)
#define CURRENT_6_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0965)
#define CURRENT_6_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0966)
#define CURRENT_6_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0967)
#define CURRENT_6_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0968)
#define CURRENT_6_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0969)
#define CURRENT_6_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096A)
#define CURRENT_6_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096B)
#define CURRENT_6_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096C)
#define CURRENT_6_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096D)
#define CURRENT_6_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096E)
#define CURRENT_6_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x096F)
#define CURRENT_7_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0970)
#define CURRENT_7_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0971)
#define CURRENT_7_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0972)
#define CURRENT_7_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0973)
#define CURRENT_7_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0974)
#define CURRENT_7_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0975)
#define CURRENT_7_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0976)
#define CURRENT_7_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0977)
#define CURRENT_7_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0978)
#define CURRENT_7_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0979)
#define CURRENT_7_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097A)
#define CURRENT_7_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097B)
#define CURRENT_7_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097C)
#define CURRENT_7_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097D)
#define CURRENT_7_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097E)
#define CURRENT_7_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x097F)
#define CURRENT_8_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0980)
#define CURRENT_8_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0981)
#define CURRENT_8_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0982)
#define CURRENT_8_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0983)
#define CURRENT_8_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0984)
#define CURRENT_8_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0985)
#define CURRENT_8_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0986)
#define CURRENT_8_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0987)
#define CURRENT_8_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0988)
#define CURRENT_8_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0989)
#define CURRENT_8_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098A)
#define CURRENT_8_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098B)
#define CURRENT_8_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098C)
#define CURRENT_8_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098D)
#define CURRENT_8_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098E)
#define CURRENT_8_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x098F)
#define CURRENT_9_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0990)
#define CURRENT_9_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0991)
#define CURRENT_9_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0992)
#define CURRENT_9_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0993)
#define CURRENT_9_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0994)
#define CURRENT_9_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0995)
#define CURRENT_9_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0996)
#define CURRENT_9_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0997)
#define CURRENT_9_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0998)
#define CURRENT_9_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID     CCPU_TO_LE16(0x0999)
#define CURRENT_9_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099A)
#define CURRENT_9_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099B)
#define CURRENT_9_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099C)
#define CURRENT_9_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099D)
#define CURRENT_9_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099E)
#define CURRENT_9_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x099F)
#define CURRENT_10_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A0)
#define CURRENT_10_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A1)
#define CURRENT_10_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A2)
#define CURRENT_10_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A3)
#define CURRENT_10_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A4)
#define CURRENT_10_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A5)
#define CURRENT_10_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A6)
#define CURRENT_10_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A7)
#define CURRENT_10_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A8)
#define CURRENT_10_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09A9)
#define CURRENT_10_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AA)
#define CURRENT_10_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AB)
#define CURRENT_10_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AC)
#define CURRENT_10_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AD)
#define CURRENT_10_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AE)
#define CURRENT_10_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09AF)
#define CURRENT_11_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B0)
#define CURRENT_11_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B1)
#define CURRENT_11_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B2)
#define CURRENT_11_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B3)
#define CURRENT_11_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B4)
#define CURRENT_11_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B5)
#define CURRENT_11_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B6)
#define CURRENT_11_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B7)
#define CURRENT_11_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B8)
#define CURRENT_11_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09B9)
#define CURRENT_11_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BA)
#define CURRENT_11_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BB)
#define CURRENT_11_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BC)
#define CURRENT_11_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BD)
#define CURRENT_11_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BE)
#define CURRENT_11_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09BF)
#define CURRENT_12_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C0)
#define CURRENT_12_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C1)
#define CURRENT_12_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C2)
#define CURRENT_12_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C3)
#define CURRENT_12_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C4)
#define CURRENT_12_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C5)
#define CURRENT_12_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C6)
#define CURRENT_12_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C7)
#define CURRENT_12_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C8)
#define CURRENT_12_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09C9)
#define CURRENT_12_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CA)
#define CURRENT_12_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CB)
#define CURRENT_12_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CC)
#define CURRENT_12_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CD)
#define CURRENT_12_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CE)
#define CURRENT_12_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09CF)
#define CURRENT_13_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D0)
#define CURRENT_13_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D1)
#define CURRENT_13_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D2)
#define CURRENT_13_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D3)
#define CURRENT_13_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D4)
#define CURRENT_13_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D5)
#define CURRENT_13_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D6)
#define CURRENT_13_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D7)
#define CURRENT_13_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D8)
#define CURRENT_13_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09D9)
#define CURRENT_13_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DA)
#define CURRENT_13_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DB)
#define CURRENT_13_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DC)
#define CURRENT_13_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DD)
#define CURRENT_13_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DE)
#define CURRENT_13_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09DF)
#define CURRENT_14_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E0)
#define CURRENT_14_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E1)
#define CURRENT_14_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E2)
#define CURRENT_14_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E3)
#define CURRENT_14_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E4)
#define CURRENT_14_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E5)
#define CURRENT_14_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E6)
#define CURRENT_14_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E7)
#define CURRENT_14_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E8)
#define CURRENT_14_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09E9)
#define CURRENT_14_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09EA)
#define CURRENT_14_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09EB)
#define CURRENT_14_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09EC)
#define CURRENT_14_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09ED)
#define CURRENT_14_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09EE)
#define CURRENT_14_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09EF)
#define CURRENT_15_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F0)
#define CURRENT_15_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F1)
#define CURRENT_15_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F2)
#define CURRENT_15_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F3)
#define CURRENT_15_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F4)
#define CURRENT_15_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F5)
#define CURRENT_15_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F6)
#define CURRENT_15_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F7)
#define CURRENT_15_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F8)
#define CURRENT_15_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID    CCPU_TO_LE16(0x09F9)
#define CURRENT_15_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FA)
#define CURRENT_15_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FB)
#define CURRENT_15_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FC)
#define CURRENT_15_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FD)
#define CURRENT_15_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FE)
#define CURRENT_15_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID   CCPU_TO_LE16(0x09FF)

#define DEFINE_BLOCK_RECEIVED_INFORMATION_ATTRIBUTS_SET() \
  DEFINE_ATTRIBUTE(currentNoTierBlock0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentNoTierBlock15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_NO_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID, ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier1Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_1_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier2Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_2_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier3Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_3_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier4Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_4_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier5Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_5_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier6Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_6_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier7Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_7_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier8Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_8_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block0SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block1SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block2SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block3SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block4SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block5SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block6SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block7SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block8SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block9SummationReceived,     ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,    ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block10SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block11SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block12SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block13SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block14SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier9Block15SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_9_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier10Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_10_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier11Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_11_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier12Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_12_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier13Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_13_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier14Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_14_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block0SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_0_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block1SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_1_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block2SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_2_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block3SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_3_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block4SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_4_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block5SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_5_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block6SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_6_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block7SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_7_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block8SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_8_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block9SummationReceived,    ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_9_SERVER_ATTRIBUTE_ID,   ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block10SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_10_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block11SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_11_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block12SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_12_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block13SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_13_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block14SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_14_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID), \
  DEFINE_ATTRIBUTE(currentTier15Block15SummationReceived,   ZCL_READONLY_ATTRIBUTE, CURRENT_15_TIER_BLOCK_15_SERVER_ATTRIBUTE_ID,  ZCL_U48BIT_DATA_TYPE_ID)


// Macros defined to be used as core of "REPEAT_MACRO" macro (see sysRepeatMacro.h)
#define CURRENT_NO_TIER_BLOCK_N_SUMMATION_RECEIVED(i, j) \
  struct PACK \
  { \
    ZCL_AttributeId_t   id; \
    uint8_t             type; \
    uint8_t             properties; \
    uint8_t             value[6]; \
  } currentNoTierBlock ## j ## SummationReceived;

#define CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED(i, j) \
  struct PACK \
  { \
    ZCL_AttributeId_t   id; \
    uint8_t             type; \
    uint8_t             properties; \
    uint8_t             value[6]; \
  } currentTier ## i ## Block ## j ## SummationReceived;

#define STRUCT_BLOCK_RECEIVED_INFORMATION_ATTRIBUTS_SET() \
  REPEAT_MACRO(CURRENT_NO_TIER_BLOCK_N_SUMMATION_RECEIVED, 0,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  1,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  2,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  3,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  4,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  5,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  6,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  7,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  8,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  9,  16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  10, 16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  11, 16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  12, 16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  13, 16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  14, 16) \
  REPEAT_MACRO(CURRENT_TIER_N_BLOCK_N_SUMMATION_RECEIVED,  15, 16)

#endif //_SIMPLEMETERINGCLUSTERATTRSET_H