#ifndef N_DEVICEINFO_BINDINGS_H
#define N_DEVICEINFO_BINDINGS_H

// This
#define N_DeviceInfo_Subscribe N_DeviceInfo_Subscribe_Impl
#define N_DeviceInfo_GetStackVersion N_DeviceInfo_GetStackVersion_Impl
#define N_DeviceInfo_GetTouchlinkRssiCorrection N_DeviceInfo_GetTouchlinkRssiCorrection_Impl
#define N_DeviceInfo_GetTouchlinkRssiThreshold N_DeviceInfo_GetTouchlinkRssiThreshold_Impl
#define N_DeviceInfo_GetNetworkPanId N_DeviceInfo_GetNetworkPanId_Impl
#define N_DeviceInfo_GetNetworkExtendedPanId N_DeviceInfo_GetNetworkExtendedPanId_Impl
#define N_DeviceInfo_GetNetworkAddress N_DeviceInfo_GetNetworkAddress_Impl
#define N_DeviceInfo_GetParentNetworkAddress N_DeviceInfo_GetParentNetworkAddress_Impl
#define N_DeviceInfo_GetIEEEAddress N_DeviceInfo_GetIEEEAddress_Impl
#define N_DeviceInfo_GetParentIEEEAddress N_DeviceInfo_GetParentIEEEAddress_Impl
#define N_DeviceInfo_GetNetworkChannel N_DeviceInfo_GetNetworkChannel_Impl
#define N_DeviceInfo_GetNetworkUpdateId N_DeviceInfo_GetNetworkUpdateId_Impl
#define N_DeviceInfo_IsFactoryNew N_DeviceInfo_IsFactoryNew_Impl
#define N_DeviceInfo_IsEndDevice N_DeviceInfo_IsEndDevice_Impl
#define N_DeviceInfo_GetPrimaryChannelMask N_DeviceInfo_GetPrimaryChannelMask_Impl
#define N_DeviceInfo_GetSecondaryChannelMask N_DeviceInfo_GetSecondaryChannelMask_Impl
#define N_DeviceInfo_GetNrChannelsInChannelMask N_DeviceInfo_GetNrChannelsInChannelMask_Impl
#define N_DeviceInfo_GetChannelForIndex N_DeviceInfo_GetChannelForIndex_Impl
#define N_DeviceInfo_IsChannelInMask N_DeviceInfo_IsChannelInMask_Impl
#define N_DeviceInfo_IsAddressAssignmentCapable N_DeviceInfo_IsAddressAssignmentCapable_Impl
#define N_DeviceInfo_CanBeLinkInitiator N_DeviceInfo_CanBeLinkInitiator_Impl
#define N_DeviceInfo_GetTouchlinkZerodBmTransmitPower N_DeviceInfo_GetTouchlinkZerodBmTransmitPower_Impl
#define N_DeviceInfo_GetTrustCenterMode N_DeviceInfo_GetTrustCenterMode_Impl

#define N_DeviceInfo_SetTouchlinkRssiCorrection N_DeviceInfo_SetTouchlinkRssiCorrection_Impl
#define N_DeviceInfo_SetTouchlinkRssiThreshold N_DeviceInfo_SetTouchlinkRssiThreshold_Impl
#define N_DeviceInfo_SetNetworkPanId N_DeviceInfo_SetNetworkPanId_Impl
#define N_DeviceInfo_SetNetworkExtendedPanId N_DeviceInfo_SetNetworkExtendedPanId_Impl
#define N_DeviceInfo_SetNetworkAddress N_DeviceInfo_SetNetworkAddress_Impl
#define N_DeviceInfo_SetParentNetworkAddress N_DeviceInfo_SetParentNetworkAddress_Impl
#define N_DeviceInfo_SetNetworkChannel N_DeviceInfo_SetNetworkChannel_Impl
#define N_DeviceInfo_SetNetworkUpdateId N_DeviceInfo_SetNetworkUpdateId_Impl
#define N_DeviceInfo_SetFactoryNew N_DeviceInfo_SetFactoryNew_Impl
#define N_DeviceInfo_SetPrimaryChannelMask N_DeviceInfo_SetPrimaryChannelMask_Impl
#define N_DeviceInfo_SetSecondaryChannelMask N_DeviceInfo_SetSecondaryChannelMask_Impl
#define N_DeviceInfo_SetParentIEEEAddress N_DeviceInfo_SetParentIEEEAddress_Impl
#define N_DeviceInfo_SetCanBeLinkInitiator N_DeviceInfo_SetCanBeLinkInitiator_Impl
#define N_DeviceInfo_SetAddressAssignmentCapable N_DeviceInfo_SetAddressAssignmentCapable_Impl
#define N_DeviceInfo_SetTrustCenterMode N_DeviceInfo_SetTrustCenterMode_Impl
#define N_DeviceInfo_GetProfileIdForEndpoint N_DeviceInfo_GetProfileIdForEndpoint_Impl

#ifdef TESTHARNESS
    #define NLME_GetExtAddr N_DeviceInfo_Wrapper_NLME_GetExtAddr

    #define N_Flash_ItemInit N_Flash_Stub_ItemInit
    #define N_Flash_Read N_Flash_Stub_Read
    #define N_Flash_Write N_Flash_Stub_Write
#else
    #define S_Nv_ItemInit S_Nv_ItemInit_Impl
    #define S_Nv_Write S_Nv_Write_Impl
#endif

#endif  /*N_DEVICEINFO_BINDINGS_H*/