#ifndef N_SOURCEROUTING_BINDINGS_H
#define N_SOURCEROUTING_BINDINGS_H
// implemented interface(s)
#define N_SourceRouting_Subscribe N_SourceRouting_Subscribe_Impl
#define N_SourceRouting_SendManyToOneRouteRequest N_SourceRouting_SendManyToOneRouteRequest_Impl
#define N_SourceRouting_SetRelayList N_SourceRouting_SetRelayList_Impl
#define N_SourceRouting_ClearRelayList N_SourceRouting_ClearRelayList_Impl

#endif // N_SOURCEROUTING_H
